name: CI/CD Pipeline for Local Server

on:
  push:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies
        run: |
          pip install pytest pytest-md pytest-emoji


      - name: Run tests
        run: |
          pytest tests.py  
